Add UI overlay buttons for drawing powers.
spirit-island/spirit-island-mod pull request #12
Opened 2021-02-03 21:09 UTC by tomprince

2021-02-03 21:13 UTC, iakona commented
you're missing a save state change

2021-02-03 21:14 UTC, iakona reviewed
you're missing a save state change

2021-02-03 21:14 UTC, iakona commented on ui.xml
> +        <Button onClick="MajorPowerUI" textAlignment="MiddleLeft">Draw Major Power</Button>
why are these alignments not `MiddleCenter`?

2021-02-03 21:19 UTC, iakona commented on ui.xml
> +<Panel id="panelPowerDraw" visibility="Invisible" allowDragging="true" width="120" height="60" rectAlignment="MiddleLeft" offsetXY="0 -40">
do you have a screenshot of how this looks? because offhand it looks like those numbers will conflict with the player names in the top right corner?

2021-02-03 21:24 UTC, iakona commented
this UI should probably be enabled by default so go ahead and add a hookup into `enableUI()`

2021-02-03 21:49 UTC, tomprince commented
The buttons are on the left, under the tools, so I think left aligned text makes sense.
![power-draw](https://user-images.githubusercontent.com/283816/106813957-e87d8100-662e-11eb-92cb-1989f0157b68.jpg)

2021-02-03 21:52 UTC, tomprince commented
> you're missing a save state change

I don't think so? I think I've also hooked it up in the default UI.

2021-02-04 08:12 UTC, tomprince commented
I want to refactor this code a bit, to make it possible to draw 6 minors or 2 majors more easily.

2021-02-05 01:12 UTC, tomprince commented
This could be improved if https://tabletopsimulator.nolt.io/307 were to be implemented (we wouldn't need so many different functions to implement this behavior).

2021-02-05 03:17 UTC, iakona requested changes
can you please middle align button text?

2021-02-05 15:54 UTC, iakona approved these changes

2021-02-05 16:43 UTC, merged